services:
  bot:
    build:
      context: ./bot
    container_name: retail_bot
    restart: unless-stopped
    networks:
      - retail_mesh
    env_file:
      - .env

networks:
  retail_mesh:
    driver: bridge