# Generated by Django 6.0.5 on 2026-05-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_address_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
