[project]
name = "retail-api"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "django>=5.0.0",
    "djangorestframework>=3.15.0",
    "django-filter>=24.0",
    "psycopg[binary]>=3.1.0",
    "pytest>=8.0.0",
    "pytest-django>=4.8.0",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest-cov",
    "factory-boy",
]

[tool.setuptools]
packages = ["core", "store"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"
python_files = ["test_*.py", "*_test.py"]
# Output the report to the terminal and omit Django boilerplate
addopts = "--cov=. --cov-report=term-missing"

[tool.coverage.run]
omit = [
    "manage.py",
    "core/asgi.py",
    "core/wsgi.py",
    "*/migrations/*"
]
[tool.ruff]
line-length = 88
target-version = "py313"
exclude = [
    ".git",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "*/migrations/*",
]

[tool.ruff.lint]
select = ["F", "E", "I"]
ignore = []
